import type { Class, Professor, Task, User } from '../types/entities';
import type { Categoria } from '../types/Categoria';

const sampleClasses: Class[] = [
   {
      id: '1a2b3c4d-0001',
      title: 'Introducción a la Programación',
      description:
         'Aprende los conceptos básicos de programación con JavaScript.',
      teacher: { id: 'prof-001', name: 'Juan Pérez' } as Professor,
      students: [
         { id: 'user-101', name: 'Ana' },
         { id: 'user-102', name: 'Carlos' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-01', nombre: 'Tecnología' } as Categoria,
      createdAt: new Date('2024-09-01T09:00:00'),
   },
   {
      id: '1a2b3c4d-0002',
      title: 'Historia del Arte',
      description:
         'Estudia las principales corrientes artísticas desde el Renacimiento hasta hoy.',
      teacher: { id: 'prof-002', name: 'María López' } as Professor,
      students: [
         { id: 'user-103', name: 'Lucía' },
         { id: 'user-104', name: 'Jorge' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-02', nombre: 'Historia' } as Categoria,
      createdAt: new Date('2024-09-02T10:00:00'),
   },
   {
      id: '1a2b3c4d-0003',
      title: 'Matemática Financiera',
      description: 'Conocé cómo aplicar fórmulas financieras en el mundo real.',
      teacher: { id: 'prof-003', name: 'Carlos Sánchez' } as Professor,
      students: [{ id: 'user-105', name: 'Matías' }] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-03', nombre: 'Matemática' } as Categoria,
      createdAt: new Date('2024-09-03T11:00:00'),
   },
   {
      id: '1a2b3c4d-0004',
      title: 'Física Cuántica Básica',
      description:
         'Una introducción accesible a los fundamentos de la física moderna.',
      teacher: { id: 'prof-004', name: 'Sofía Martínez' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-01', nombre: 'Matemática' } as Categoria,
      createdAt: new Date('2024-09-04T12:00:00'),
   },
   {
      id: '1a2b3c4d-0005',
      title: 'Literatura Contemporánea',
      description: 'Análisis de obras destacadas del siglo XXI.',
      teacher: { id: 'prof-005', name: 'Germán Díaz' } as Professor,
      students: [
         { id: 'user-106', name: 'Valentina' },
         { id: 'user-107', name: 'Martín' },
         { id: 'user-108', name: 'Florencia' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-02', nombre: 'Lenguajes' } as Categoria,
      createdAt: new Date('2024-09-05T13:00:00'),
   },
   {
      id: '1a2b3c4d-0006',
      title: 'Biología Marina',
      description: 'Explora los ecosistemas marinos y su biodiversidad.',
      teacher: { id: 'prof-006', name: 'Ignacio Suárez' } as Professor,
      students: [{ id: 'user-109', name: 'Camila' }] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-04', nombre: 'Ciencia' } as Categoria,
      createdAt: new Date('2024-09-06T14:00:00'),
   },
   {
      id: '1a2b3c4d-0007',
      title: 'Fotografía Digital',
      description:
         'Técnicas y herramientas para capturar imágenes impactantes.',
      teacher: { id: 'prof-007', name: 'Laura Torres' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-05', nombre: 'Tecnología' } as Categoria,
      createdAt: new Date('2024-09-07T15:00:00'),
   },
   {
      id: '1a2b3c4d-0008',
      title: 'Cocina Internacional',
      description: 'Prepará platos de distintas partes del mundo.',
      teacher: { id: 'prof-008', name: 'Diego Rodríguez' } as Professor,
      students: [
         { id: 'user-110', name: 'Federico' },
         { id: 'user-111', name: 'Laura' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-06', nombre: 'Salud' } as Categoria,
      createdAt: new Date('2024-09-08T16:00:00'),
   },
   {
      id: '1a2b3c4d-0009',
      title: 'Diseño UX/UI',
      description:
         'Aprende los principios clave para crear interfaces efectivas.',
      teacher: { id: 'prof-009', name: 'Andrea Gómez' } as Professor,
      students: [
         { id: 'user-112', name: 'Bruno' },
         { id: 'user-113', name: 'Julieta' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-01', nombre: 'Tecnología' } as Categoria,
      createdAt: new Date('2024-09-09T17:00:00'),
   },
   {
      id: '1a2b3c4d-0010',
      title: 'Psicología del Desarrollo',
      description: 'Un recorrido por las etapas del crecimiento humano.',
      teacher: { id: 'prof-010', name: 'Ricardo Herrera' } as Professor,
      students: [{ id: 'user-114', name: 'Sabrina' }] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-07', nombre: 'Salud' } as Categoria,
      createdAt: new Date('2024-09-10T18:00:00'),
   },
   {
      id: '1a2b3c4d-0011',
      title: 'Teoría Musical Básica',
      description: 'Conocé los fundamentos del lenguaje musical y la notación.',
      teacher: { id: 'prof-011', name: 'Esteban Correa' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-08', nombre: 'Música' } as Categoria,
      createdAt: new Date('2024-09-11T08:00:00'),
   },
   {
      id: '1a2b3c4d-0012',
      title: 'Análisis de Datos con Python',
      description:
         'Procesamiento de datos y visualización con bibliotecas modernas.',
      teacher: { id: 'prof-012', name: 'Paula Ríos' } as Professor,
      students: [
         { id: 'user-115', name: 'Tomás' },
         { id: 'user-116', name: 'Elena' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-09', nombre: 'Tecnología' } as Categoria,
      createdAt: new Date('2024-09-12T08:00:00'),
   },
   {
      id: '1a2b3c4d-0013',
      title: 'Geografía Física del Uruguay',
      description: 'Relieve, clima y recursos naturales de nuestro país.',
      teacher: { id: 'prof-013', name: 'Luciana Bentancor' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-10', nombre: 'Geografía' } as Categoria,
      createdAt: new Date('2024-09-13T08:00:00'),
   },
   {
      id: '1a2b3c4d-0014',
      title: 'Economía Personal',
      description:
         'Aprendé a administrar tus ingresos y ahorrar con inteligencia.',
      teacher: { id: 'prof-014', name: 'Mario Paredes' } as Professor,
      students: [{ id: 'user-117', name: 'Romina' }] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-11', nombre: 'Finanzas' } as Categoria,
      createdAt: new Date('2024-09-14T08:00:00'),
   },
   {
      id: '1a2b3c4d-0015',
      title: 'Inglés Conversacional A1',
      description: 'Comenzá a hablar inglés desde cero con situaciones reales.',
      teacher: { id: 'prof-015', name: 'Victoria Ayala' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-12', nombre: 'Lenguajes' } as Categoria,
      createdAt: new Date('2024-09-15T08:00:00'),
   },
   {
      id: '1a2b3c4d-0016',
      title: 'Técnicas de Primeros Auxilios',
      description: 'Respondé a emergencias con seguridad y eficacia.',
      teacher: { id: 'prof-016', name: 'Héctor Gómez' } as Professor,
      students: [
         { id: 'user-118', name: 'Daniela' },
         { id: 'user-119', name: 'Nicolás' },
      ] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-13', nombre: 'Salud' } as Categoria,
      createdAt: new Date('2024-09-16T08:00:00'),
   },
   {
      id: '1a2b3c4d-0017',
      title: 'Fútbol y Estrategia',
      description: 'Entrenamiento técnico y táctico para equipos de base.',
      teacher: { id: 'prof-017', name: 'Santiago Ferrer' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-14', nombre: 'Deporte' } as Categoria,
      createdAt: new Date('2024-09-17T08:00:00'),
   },
   {
      id: '1a2b3c4d-0018',
      title: 'Astronomía para Principiantes',
      description: 'Explorá el universo y aprendé sobre estrellas y planetas.',
      teacher: { id: 'prof-018', name: 'Mónica Etcheverry' } as Professor,
      students: [{ id: 'user-120', name: 'Iván' }] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-15', nombre: 'Ciencia' } as Categoria,
      createdAt: new Date('2024-09-18T08:00:00'),
   },
   {
      id: '1a2b3c4d-0019',
      title: 'Introducción al Ajedrez',
      description:
         'Aprendé a jugar ajedrez desde las reglas básicas hasta tácticas iniciales.',
      teacher: { id: 'prof-019', name: 'Silvia Ortiz' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-16', nombre: 'Deporte' } as Categoria,
      createdAt: new Date('2024-09-19T08:00:00'),
   },
   {
      id: '1a2b3c4d-0020',
      title: 'Redacción Académica',
      description: 'Mejorá tu escritura formal para ensayos y trabajos.',
      teacher: { id: 'prof-020', name: 'Marcelo Piñeyro' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-17', nombre: 'Lenguajes' } as Categoria,
      createdAt: new Date('2024-09-20T08:00:00'),
   },
   {
      id: '1a2b3c4d-0021',
      title: 'Guitarra Inicial',
      description: 'Domina acordes básicos y ritmos populares.',
      teacher: { id: 'prof-021', name: 'Natalia Viera' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-18', nombre: 'Música' } as Categoria,
      createdAt: new Date('2024-09-21T08:00:00'),
   },
   {
      id: '1a2b3c4d-0022',
      title: 'Estadística Aplicada',
      description: 'Analizá datos reales con herramientas estadísticas.',
      teacher: { id: 'prof-022', name: 'Julián Morales' } as Professor,
      students: [{ id: 'user-121', name: 'Agustina' }] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-19', nombre: 'Matemática' } as Categoria,
      createdAt: new Date('2024-09-22T08:00:00'),
   },
   {
      id: '1a2b3c4d-0023',
      title: 'Nutrición y Bienestar',
      description:
         'Descubrí cómo llevar una alimentación saludable y balanceada.',
      teacher: { id: 'prof-023', name: 'Carla Medina' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-20', nombre: 'Salud' } as Categoria,
      createdAt: new Date('2024-09-23T08:00:00'),
   },
   {
      id: '1a2b3c4d-0024',
      title: 'La Segunda Guerra Mundial',
      description:
         'Analizá las causas, desarrollo y consecuencias del conflicto global.',
      teacher: { id: 'prof-024', name: 'Andrés Pérez' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-21', nombre: 'Historia' } as Categoria,
      createdAt: new Date('2024-09-24T08:00:00'),
   },
   {
      id: '1a2b3c4d-0025',
      title: 'JavaScript Intermedio',
      description: 'Avanzá en tu dominio de JavaScript con proyectos reales.',
      teacher: { id: 'prof-025', name: 'Emilia Castro' } as Professor,
      students: [] as User[],
      tasks: [] as Task[],
      category: { id: 'cat-22', nombre: 'Tecnología' } as Categoria,
      createdAt: new Date('2024-09-25T08:00:00'),
   },
];

export default sampleClasses;
