const materiasPorCategoria: Record<
   string,
   { nombre: string; imagen: string }[]
> = {
   Musica: [
      { nombre: 'Teoría Musical', imagen: '/materia-test.jpg' },
      { nombre: 'Historia de la música', imagen: '/materia-test.jpg' },
      { nombre: 'Composición y Armonía', imagen: '/materia-test.jpg' },
      { nombre: 'Guitarra', imagen: '/materia-test.jpg' },
      { nombre: 'Piano', imagen: '/materia-test.jpg' },
      { nombre: 'Producción Musical Digital', imagen: '/materia-test.jpg' },
      { nombre: 'Canto y Técnica Vocal', imagen: '/materia-test.jpg' },
      { nombre: 'Música del Mundo', imagen: '/materia-test.jpg' },
      { nombre: 'Apreciación Musical', imagen: '/materia-test.jpg' },
   ],
   Matematica: [
      { nombre: 'Álgebra', imagen: '/materia-test.jpg' },
      { nombre: 'Geometría', imagen: '/materia-test.jpg' },
      { nombre: 'Cálculo Diferencial', imagen: '/materia-test.jpg' },
      { nombre: 'Estadística', imagen: '/materia-test.jpg' },
      { nombre: 'Aritmética Financiera', imagen: '/materia-test.jpg' },
      { nombre: 'Probabilidades', imagen: '/materia-test.jpg' },
      { nombre: 'Lógica Matemática', imagen: '/materia-test.jpg' },
      { nombre: 'Trigonometría', imagen: '/materia-test.jpg' },
      { nombre: 'Matemática Discreta', imagen: '/materia-test.jpg' },
   ],
   Ciencia: [
      { nombre: 'Física Clásica', imagen: '/materia-test.jpg' },
      { nombre: 'Química General', imagen: '/materia-test.jpg' },
      { nombre: 'Biología Celular', imagen: '/materia-test.jpg' },
      { nombre: 'Astronomía', imagen: '/materia-test.jpg' },
      { nombre: 'Ciencias de la Tierra', imagen: '/materia-test.jpg' },
      { nombre: 'Ecología', imagen: '/materia-test.jpg' },
      { nombre: 'Genética', imagen: '/materia-test.jpg' },
      { nombre: 'Física Cuántica', imagen: '/materia-test.jpg' },
      { nombre: 'Energías Renovables', imagen: '/materia-test.jpg' },
   ],
   Finanzas: [
      { nombre: 'Finanzas Personales', imagen: '/materia-test.jpg' },
      {
         nombre: 'Educación Financiera para Jóvenes',
         imagen: '/materia-test.jpg',
      },
      { nombre: 'Contabilidad Básica', imagen: '/materia-test.jpg' },
      { nombre: 'Inversiones y Bolsa', imagen: '/materia-test.jpg' },
      { nombre: 'Presupuesto Familiar', imagen: '/materia-test.jpg' },
      { nombre: 'Economía Doméstica', imagen: '/materia-test.jpg' },
      { nombre: 'Criptomonedas', imagen: '/materia-test.jpg' },
      { nombre: 'Emprendimientos y Finanzas', imagen: '/materia-test.jpg' },
      { nombre: 'Impuestos y Declaraciones', imagen: '/materia-test.jpg' },
   ],
   Lenguajes: [
      { nombre: 'Gramática Española', imagen: '/materia-test.jpg' },
      { nombre: 'Escritura Creativa', imagen: '/materia-test.jpg' },
      { nombre: 'Comprensión Lectora', imagen: '/materia-test.jpg' },
      { nombre: 'Comunicación Oral', imagen: '/materia-test.jpg' },
      { nombre: 'Literatura Latinoamericana', imagen: '/materia-test.jpg' },
      { nombre: 'Análisis de Textos', imagen: '/materia-test.jpg' },
      { nombre: 'Ortografía y Redacción', imagen: '/materia-test.jpg' },
      { nombre: 'Lengua Inglesa', imagen: '/materia-test.jpg' },
      { nombre: 'Argumentación y Retórica', imagen: '/materia-test.jpg' },
   ],
   Deporte: [
      { nombre: 'Técnicas de Fútbol', imagen: '/materia-test.jpg' },
      { nombre: 'Fundamentos del Atletismo', imagen: '/materia-test.jpg' },
      { nombre: 'Reglas del Básquetbol', imagen: '/materia-test.jpg' },
      { nombre: 'Preparación Física', imagen: '/materia-test.jpg' },
      { nombre: 'Nutrición Deportiva', imagen: '/materia-test.jpg' },
      { nombre: 'Entrenamiento Funcional', imagen: '/materia-test.jpg' },
      { nombre: 'Yoga y Flexibilidad', imagen: '/materia-test.jpg' },
      { nombre: 'Salud Mental y Deporte', imagen: '/materia-test.jpg' },
      { nombre: 'Historia del Deporte', imagen: '/materia-test.jpg' },
   ],
   Historia: [
      { nombre: 'Historia Antigua', imagen: '/materia-test.jpg' },
      { nombre: 'Edad Media Europea', imagen: '/materia-test.jpg' },
      { nombre: 'Historia de América Latina', imagen: '/materia-test.jpg' },
      { nombre: 'Revolución Francesa', imagen: '/materia-test.jpg' },
      { nombre: 'Guerras Mundiales', imagen: '/materia-test.jpg' },
      { nombre: 'Historia del Arte', imagen: '/materia-test.jpg' },
      { nombre: 'Civilizaciones Precolombinas', imagen: '/materia-test.jpg' },
      { nombre: 'Historia de Uruguay', imagen: '/materia-test.jpg' },
      { nombre: 'Historia Contemporánea', imagen: '/materia-test.jpg' },
   ],
   Geografia: [
      { nombre: 'Geografía Física', imagen: '/materia-test.jpg' },
      { nombre: 'Climas del Mundo', imagen: '/materia-test.jpg' },
      { nombre: 'Recursos Naturales', imagen: '/materia-test.jpg' },
      { nombre: 'Geografía Humana', imagen: '/materia-test.jpg' },
      { nombre: 'Mapas y Cartografía', imagen: '/materia-test.jpg' },
      { nombre: 'Geopolítica Moderna', imagen: '/materia-test.jpg' },
      { nombre: 'Regiones Naturales', imagen: '/materia-test.jpg' },
      { nombre: 'Población y Migración', imagen: '/materia-test.jpg' },
      { nombre: 'Territorio y Medio Ambiente', imagen: '/materia-test.jpg' },
   ],
   Salud: [
      { nombre: 'Primeros Auxilios', imagen: '/materia-test.jpg' },
      { nombre: 'Higiene Personal', imagen: '/materia-test.jpg' },
      { nombre: 'Educación Sexual Integral', imagen: '/materia-test.jpg' },
      { nombre: 'Nutrición y Dietética', imagen: '/materia-test.jpg' },
      { nombre: 'Salud Mental', imagen: '/materia-test.jpg' },
      { nombre: 'Prevención de Enfermedades', imagen: '/materia-test.jpg' },
      { nombre: 'Estilo de Vida Saludable', imagen: '/materia-test.jpg' },
      { nombre: 'Actividad Física y Salud', imagen: '/materia-test.jpg' },
      { nombre: 'Autoestima y Bienestar', imagen: '/materia-test.jpg' },
   ],
};

export default materiasPorCategoria;
